version: '3.8'

services:

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass su7vu9xyzl0bzrur5jq
    networks:
      busynet:
        aliases:
          - redis.service


networks:
  busynet:
    external: true
    name: busynet 


