version: "3.1"
services:

  pgsql:
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: su7vu9xyzl0bzrur5jq
      PGDATA: /data/pgsql/pgdata
    volumes:
      - ./data/pgsql:/data/pgsql
    networks:
      busynet:
        aliases:
          - postgres.service

networks:
  busynet:
    external: true
    name: busynet